### ISSUE TITLE
Password included in token from jwt strategy example

### ISSUE THREAD

**Issue by ChoffaH** [shaj13/go-guardian#102]
### What version of Go are you using (`go version`)?

<pre>
$ go version
1.16
</pre>

### Does this issue reproduce with the latest release?
Yes

### What version of Go-Guardian are you using ?

<pre>
Go-Guardian Version: 
v2.11.2
</pre>

### What did you do?

Run the jwt token example in the repo with basic login.

### What did you expect to see?

A token without password.

### What did you see instead?

The password included in plain text in the payload of the token:
```json
{
  "Extensions": {
    "x-go-guardian-basic-password": [
      "admin"
    ]
  },
  "Groups": null,
  "ID": "1",
  "Name": "admin",
  "aud": [
    ""
  ],
  "exp": 1615318474,
  "iat": 1615318174,
  "nbf": 1615318174,
  "sub": "1"
}
```

**Comment by shaj13** [comment]
@ChoffaH good  catch, basic should avoid store sensitive data in user extension, 
need to create a cache struct entry and when the user authenticated push that entry the cache instead of auth info. 
Starting point https://github.com/shaj13/go-guardian/blob/master/auth/strategies/basic/cached.go#L66
```go
type entry struct {
  user auth.Info 
  password string 
}
// .... 
```
 I would love to see a PR

**Comment by shaj13** [comment]
@ChoffaH fixed

**Comment by sweco-secfha** [comment]
@shaj13 Great! I haven't had the time to try making a PR for this so thank you! 😃

**Comment by ChoffaH** [comment]
@shaj13 Great! I haven't had the time to try making a PR for this so thank you! 😃
