### ISSUE TITLE
When Basic authentication fails, the `WWW-Authenticate` header is not returned

### ISSUE THREAD

**Issue by gczobel-f5** [shaj13/go-guardian#33]
Based on https://tools.ietf.org/html/rfc7235#section-4.1, when 401 is returned the `WWW-Authenticate` header must be in the response.

https://tools.ietf.org/html/rfc7235#section-3.1 "containing at least one challenge applicable to the target resource"

**Comment by shaj13** [comment]
@gczobel-f5 
FYI, The library does not respond to the end-user and must set behind the scene as an authentication daemon since its not mount any route/routers.

There a plan to expose a function under auth pkg to set the appropriate HTTP header based on passed args in the next release. 
right now library only sets `WWW-Authenticate` for [digest strategy](https://pkg.go.dev/github.com/shaj13/go-guardian@v1.2.1/auth/strategies/digest?tab=doc#Strategy.WWWAuthenticate) and it must be invoked by your application code.

keep this open for tracking the progress.
